### ISSUE TITLE
iOS Toolbar for Editor

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#137]
iPhone (in order):
- Add Media, Bold, Italics, Underline, Link/Unlink, Quote, UL, OL
- HTML button

iPad (in order):
- Add Media, Bold, Italics, Underline, Link/Unlink, Quote, UL, OL, Strikethru, More
- HTML button
  _________

~~Toolbar richtext btns: https://cloudup.com/cuapovMJQs8~~
~~HTML btn: https://cloudup.com/cM7kp0P6fwh~~
*btns have new active and default colors. Please update color of toolbar as well.

**Comment by tahseen0amin** [comment]
can we not have HTML button in toolbar ?
