### ISSUE TITLE
Re-enable support for uploading videos

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#14]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1792

In the last major version of the app, we added a new media picker to the editor (for uploading images), but we disabled video uploads because they weren't working very well.

In #1779 @koke added support for a new REST API for media. We should be able to use this to do a better job of video uploads (edit: backend still needs work though). We can then re-enable the ability to select videos in the media picker.

Some other, possibly related issues that could get fixed along the way: https://github.com/wordpress-mobile/WordPress-iOS/issues/1628 https://github.com/wordpress-mobile/WordPress-iOS/issues/433

- [x] Re-enable the ability to select videos
- [x] Use new REST API for media if possible; XML-RPC fallback
- [x] Check other video-related issues

**Comment by richardmax** [comment]
When are you planning to add video back to this app? Theres been nothing about it for months and a year has almost past since the feature was removed. Not moaning (yes ok a bit) - just asking! Its not like video is less important nowadays - tell vine!, lets move with the times guys!

**Comment by bummytime** [comment]
@richardmax Videos are imminent (https://github.com/wordpress-mobile/WordPress-iOS/pull/3503)! As of right now, they are slotted in for the WPiOS 5.1 release.

Thanks for sticking with us! :grinning:

**Comment by richardmax** [comment]
Awesome... drum role... crack open the champers.... lets get vlogging!!!!
Whens 5.1 landing?

**Comment by bummytime** [comment]
@richardmax Roughly, sometime in the middle to end of May.

**Comment by mgarza1812** [comment]
Wow, that post just made my day. 
Like on the scale of a new Star Wars trailer kinda awesome!

**Comment by astralbodies** [comment]
![Star Wars](https://cldup.com/9t-VI2nCV5.png)

**Comment by SergioEstevao** [comment]
Released on 5.1
