### ISSUE TITLE
tags aren't getting saved

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#184]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2248

Steps to reproduce:

1) Start a new post.
2) Add tags from *Options*.
3) Preview the post to ensure the tags are there.
4) Publish the post. The tags are no longer here.

I'm having trouble reproducing this but it seems like a good candidate for automated testing.  

props for reporting @wpval

**Comment by meremagee** [comment]
resolved
