### ISSUE TITLE
EditPostViewController errors with key-value coding

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#185]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2234

When compiling and running any version of this source, I seem to always encounter uncaught exceptions in key-value coding on EditPostViewController on the "attachmentButton", "categoriesButton", and "categoryLabel" properties when attempting to edit or create a post.

What am I missing that this does not work on the development, release/4.2 or release/4.3 branches?

Thanks!

**Comment by bummytime** [comment]
Not an issue anymore. Closing.
