### ISSUE TITLE
Colors of "Cancel" and "Send" when sending an email are hard to read

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#189]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2163

![image](https://cloud.githubusercontent.com/assets/437043/3759202/2ae1d602-1859-11e4-8d3b-5f3ed6c35475.png)

**Comment by bummytime** [comment]
Not an editor issue..plus it was fixed. :-)
