### ISSUE TITLE
Default to user's primary blog for post creation

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#21]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1668

Right now if a user signs in fresh without wandering down any blog menu we will default to the first blog on their list rather than the default one. Let's set it up so on first launch the first blog that shows up is their default one.

**Comment by rachelmcr** [comment]
I tested this in the latest beta v. 5.9.0.20160126 and this is no longer an issue. I logged in to the app, opening the editor, and it defaulted to my primary blog. Closed as resolved. :)
