### ISSUE TITLE
Media library access from the in-app media picker

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#230]
From a user:

>...when adding images in the app, it would be nice to have access to the media library. Not all of my images are stored on my phone. I was writing a post and wanted to use an image I previously uploaded and couldn’t. :(

**Comment by Codelica** [comment]
Are there any plans for this?  Looks like the Android version has support, so there is hope.  Maybe. :)

**Comment by bummytime** [comment]
@Codelica there is indeed hope! :-) 

This is a feature we are looking to implement in the near term. Hard to pin down an exact date, but I would say roughly Q2 of this year.

**Comment by bummytime** [comment]
Closing in favor of: https://github.com/wordpress-mobile/WordPress-iOS/issues/3456
