### ISSUE TITLE
Let the placeholder be shown outside edit mode somehow.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#242]
The placeholder is currently not visible outside of edit mode.  It would be nice for our `WPEditorView` to offer some way to configure that to also be shown outside of edit mode.

**Comment by diegoreymendez** [comment]
@meremagee - Is this necessary?  I think this may not be necessary or worth it at this time.

**Comment by diegoreymendez** [comment]
I'll close for now since I was the one who opened this ticket in the first place.

**Comment by bummytime** [comment]
:tada: :balloon:
