### ISSUE TITLE
Post formats on new post may be unavailable if accessed before fetch completes

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#254]
If you immediately view new post options before the post options data is downloaded, you are unable to set the post format for a given post unless you exit and return to the post screen. Video of this here:

https://cloudup.com/cVrr-raDJsk

Referenced here: https://github.com/wordpress-mobile/WordPress-iOS/pull/2451

>Since we need to make a network call to get the Post Formats, if you race to the options screen before the update call is completed (and we don't already have post formats cached for a specific blog), you will not see the formats list. However if you leave and go back to the options screen they will be there (and will be cached for future usage).

**Comment by diegoreymendez** [comment]
Still reproducible under iOS 9.0 by following these steps:

1. Reset the simulator.
2. Launch the app.
3. Sign in
4. As soon as you sign in, disconnect the wifi.
5. Create a new post.
6. Reconnect wifi - the post format is never loaded.

**Comment by diegoreymendez** [comment]
Fixed.
