### ISSUE TITLE
Dbl-spc to add period resets rich text

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#257]
Un-selecting bold, italic, and underline before double spacing to add period doesn't work.

Repro

- while typing a sentence, bold a word by hitting the B, then type the word
- Hit B again after completion of word to keep typing
- add a period by hitting space 2x (normal writing flow on ios)
- continue typing
- note that appending the styled word with a period (only via dbl-space, not manually) seems to reset the styling

---
Originally, adding any punctuation, even manually would reset rich-text (logged here https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/163). That has been resolved. It's just with the double space > period now.

**Comment by bummytime** [comment]
Retested on latest iOS9-only internal — seems to work now. Closing.
