### ISSUE TITLE
Rich text & delete

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#258]
backspacing from something that is richtext to something not styled maintains richtext styling.

Repro from a user: 
- Type some stuff
- tap bold and type few words
- tap bold again to turn it off, keep typing.
- then hit backspace a bunch
- when the cursor gets to the bold section it will turn bold on automatically
- but when you backspace past the bold part it doesn't turn off again

**Comment by bummytime** [comment]
Just tested in 5.7 internal and this issue seems to be fixed. Closing.
