### ISSUE TITLE
Uploaded media is not resizable in dashboard

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#266]
From a user:

>I was working on a blog post (for my self-hosted blog) in the browser when I decided I wanted to add an image from my phone. So I saved the draft and opened the post in my mobile app. (iPhone 5s, iOS 8, app version 4.3.) I added the photo, and then went back to the browser so I could put the image where I wanted it, resize it, etc.
>
When I opened the image details screen in the browser, this is what I got:
>
![screenshot-2014-09-29-11-43-15](https://cloud.githubusercontent.com/assets/154014/4478875/dcb4154c-4988-11e4-9bf6-3b0bb1b5fb59.png)
>
> There is no option to change the image size or edit the original image from this screen.
>
By contrast, if I add the image from the media library:
>
![screenshot-2014-09-29-11-49-02](https://cloud.githubusercontent.com/assets/154014/4478898/088a5e92-4989-11e4-88ae-b95ec6e86d37.png)

It looks like the fix may be as simple as adding some more attributes to the `img` element. The mobile app does this:
```html
<img src="http://bummypublic.files.wordpress.com/2014/10/img_00081.jpg" />
```
and the media picker does this:
```html
<img class="alignnone size-medium wp-image-257" src="http://bummypublic.files.wordpress.com/2014/10/img_00081.jpg?w=300" alt="IMG_0008" width="300" height="200" />
```

**Comment by rachelmcr** [comment]
In addition to the missing `Size` field, other fields are (now) also missing as reported in #752. I'm going to close this issue as a dupe since the newer issue includes some other related, missing fields.
