### ISSUE TITLE
Disallowing access to photos results in blank screen

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#28]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1489

If you disallow access to photos you are presented with a blank white screen with an empty navigation bar except with a back arrow.  I suspect the screen should look more like so (which it does when you revisit that screen):

![img_0051](https://cloud.githubusercontent.com/assets/373903/2530781/9c459c62-b52a-11e3-87e0-9ba48dd64883.PNG)

This screen is still missing a title for the nav bar.

**Comment by diegoreymendez** [comment]
Closing, as this seems not to be the case anymore.  This is what the app is showing now:

<img width="383" alt="screen shot 2016-03-08 at 1 41 09 pm" src="https://cloud.githubusercontent.com/assets/1836005/13608411/7708ba02-e533-11e5-8942-309ed81bad22.png">
