### ISSUE TITLE
Allow users to manager Publicize settings in-app

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#298]
From a user:

> The one thing that forced me to go back to the desktop view for a scheduled post I was working on is that I didn’t want to share it to Facebook, but automatically have that enabled through Publicize. I would love for there to be a way to manage that in the app itself.

**Comment by rachelmcr** [comment]
This was resolved in the main repo: https://github.com/wordpress-mobile/WordPress-iOS/issues/2698
