### ISSUE TITLE
"Done" button for publish date is cut off on iPhone 6 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#310]
From a user, title has it:

![scaled img_4699](https://cloud.githubusercontent.com/assets/154014/4707765/9ba09014-5890-11e4-997e-74aa9b76bc1c.png)

**Comment by meremagee** [comment]
this appears to be resolved. @bummytime sanity check?

**Comment by bummytime** [comment]
Sorry @meremagee, this is still an issue....it is just less bad on the iPhone 6.

**Comment by bummytime** [comment]
Fixed.
