### ISSUE TITLE
Move the source view and its title to the web view.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#335]
Right now the source view for the new visual editor is a native iOS component.  With @bummytime we agree that making this component web based makes the most sense given our current architecture.

**Comment by bummytime** [comment]
Playing devil's advocate here....is this something that can wait until we are past the 4.8 release? This is a pretty large change to be introducing now. In addition, @diegoreymendez has a nice fix here: https://github.com/wordpress-mobile/WordPress-iOS-Editor/pull/460 that might buy us a little time.

**Comment by bummytime** [comment]
@thianhlu thoughts on the question above?

**Comment by thianhlu** [comment]
Sounds good, moving out of this milestone

**Comment by diegoreymendez** [comment]
This is done.

**Comment by diegoreymendez** [comment]
Since I reopened this, and apparently for no reason, I'm closing it again.
