### ISSUE TITLE
Set filename as default "alt"

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#364]
in production editor, img ALT sets to full filepath, which isn't optimum. in visual editor, ALT is set to null, `alt=""`. For accessibility, it would be great to default to the filename or "view {filename}" so that on hover, images are more descriptive.

**Comment by SergioEstevao** [comment]
How does this change play with this https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/15

**Comment by meremagee** [comment]
#15 is largely resolved by @aerych's [img settings](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/427) work. This issue is also outdated, so closing now and we can refine once we have more usage around how people engage with the media edit settings.
