### ISSUE TITLE
Make sure the restoration of `WPPostViewController` is invisible to users.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#384]
There are some animation jumps when `WPPostViewController` is restored.  Make sure we eliminate them as much as possible.

**Comment by meremagee** [comment]
moving to 4.9 since this is more aesthetic than functional

**Comment by diegoreymendez** [comment]
I noticed that several apps show a different pre-restore image and restored VC.  Pretty standard and the effort put here may not be worth it.  Closing this.

**Comment by bummytime** [comment]
>  I noticed that several apps show a different pre-restore image and restored VC. Pretty standard and the effort put here may not be worth it. Closing this.

Agree 100%. Standard stuff
