### ISSUE TITLE
"Save draft" not an option in locally stored posts

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#393]
"Save to draft" is missing from the X dropdown while editing locally stored posts even after reconnection.

- start offline
- draft a post on editor
- hit post
- noticed that post appears on posts lists with "FAILED"
- click post title to open local draft
- connect to internet
- hit X in the top left
- see dropdown with "discard" but no option to "save to draft" as you would see with a "normal" draft

regular dropdown: https://cloudup.com/it5ms05vRus
if stored locally before reconnecting: https://cloudup.com/iEpOT_TuKLN

**Comment by diegoreymendez** [comment]
Fixed.
