### ISSUE TITLE
cancel add media > edit mode

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#405]
While editing a post, if you hit the media button then opt to cancel adding anything, you get taken back to edit mode on editor, but the keyboard isn't displayed

- edit a post
- tap add media
- cancel when on media library page
- go back to post
- cursor is inserted/post body is focused
- no keyboard
![](https://cloudup.com/cSWkrhH9TsD+)

**Comment by bummytime** [comment]
Closing since we dropped iOS7 support.
