### ISSUE TITLE
Every post published from new acct duplicated in post list

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#407]
- create account on mobile app
- write a blog post
- publish it (happened on both private and publicly published blogs)
- duplicates on post list until refresh

https://lookback.io/watch/YjEHgJk2KtArAS3yR

**Comment by bummytime** [comment]
Addressed.

**Comment by diegoreymendez** [comment]
I'm seeing this again.  Opening up.

**Comment by diegoreymendez** [comment]
Actually it's not exactly the same behaviour so I'll open a new issue.
