### ISSUE TITLE
Typing around an uploading image is not always working.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#421]
[Video showing the issue here](https://cloudup.com/cYh8ib4RNkK).

**Comment by meremagee** [comment]
can't repro immediately - moving to 4.9 - media milestone

**Comment by diegoreymendez** [comment]
@SergioEstevao - I'm reviewing old tickets and noticed this one is assigned to you.  Is this ticket still valid?

**Comment by SergioEstevao** [comment]
This is solved, so I'm closing it.
