### ISSUE TITLE
Call correct super method for WPEditorViewController viewWillDisappear

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Editor-iOS#456]
While running the static analyzer on WPiOS it caught that `WPEditorViewController`'s `viewWillDisappear:` method does not call its super method, and instead calls the super `viewDidDisappear:`.  

https://github.com/wordpress-mobile/WordPress-iOS-Editor/blob/develop/Classes/WPEditorViewController.m#L171

```
- (void)viewWillDisappear:(BOOL)animated
{
[super viewDidDisappear:animated];
// It's important to save the edit selection before the view disappears, because as soon as it
// disappears the first responder is changed.
//
[self saveEditSelection];
}
```

**Comment by SergioEstevao** [comment]
Fixed since 0.4
