### ISSUE TITLE
Imgs in title field

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#462]
User was trying to place cursor in body before adding an image, image loaded in title field (iphone4, ios7): https://lookback.io/watch/ZKyyC8yK8xLKyJbXm

Imgs are added to media library but not published in post when this happens

Can reproduce by cutting and pasting an image into the title field (user confirmed that this was _not_ how they got the issue initially): 
https://lookback.io/watch/odRGgkKfuTWikiuxE

Any way to block paste or insertion of images into title/block them entirely in title field?

**Comment by bummytime** [comment]
Closing in favor of #665
