### ISSUE TITLE
Add support for galleries

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#48]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/431

**Comment by jeremeylduvall** [comment]
@bummytime delayed follow-up here. Looks like you closed this in favor of #230 (which was closed for #3456). As far as I can tell, galleries weren't addressed in #3456. Should we re-open this one?

Mentioned in 107491-h

**Comment by bummytime** [comment]
@jeremeylduvall Yeah, as I look at this I have no idea why I closed it. 😐 It is two different things. Looks like we have this issue open right now: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/300 

Why don't we go with that one if you are good with it.

**Comment by jeremeylduvall** [comment]
Works for me! Not sure how I missed that one. Thanks!
