### ISSUE TITLE
Scheduling already drafted posts doesn't work

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#50]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/409

Maybe related to https://github.com/wordpress-mobile/WordPress-iOS/issues/66.

A user reported that posts publish immediately, after going back and forth it turns out that it happens specifically when you've already drafted a post. Once I figured that out I can replicate consistently:

* Create a post in wp-admin or elsewhere (not in app)
* Load up app, change publish date
* Buttons don't update to say "Schedule", instead just says "Update"
* If you hit Update the post is uploaded but status is still draft, time stamp is current, and the scheduled time is lost.

There's a second issue related to scheduling: even if you create the post from within the app you have to schedule it right away or else you can't. In this case the scheduled post time seems to save but since the button never changes to Schedule you can't actually "schedule" until you change the post status.

...and a third I guess: changing post status to "Published" is actually "scheduled" once you've tapped it if the post is scheduled. But the latter two are likely UX issues.

After scheduled time was changed:
![img_0673](https://f.cloud.github.com/assets/3073557/1519079/d2a1131e-4b4d-11e3-8e98-f97ddc9211fb.PNG)

When upload process has finished time stamp is changed back to current time:
![img_0674](https://f.cloud.github.com/assets/3073557/1519080/d2a2c7a4-4b4d-11e3-9f1e-4aebbd78eabf.PNG)

Unrelated to current QA but important enough for .5 I think (tagging).

**Comment by bummytime** [comment]
Another user report:

> I’ve discovered that if you save a post as a draft in the #iOS app (beta v. 4.9.0.20150223), and then schedule it to be published in the future, it will be published immediately instead.
>
> Steps to reproduce:
1. Create a new post in the iOS app
2. Save it as a draft
3. Go back to the settings and schedule it for a future date/time
4. Tap the Schedule link to schedule the post
Result: It’s published immediately instead of on the scheduled date
>
> It wasn’t a big deal for the post I was scheduling 5 minutes in the future, but when I reproduced it on a post being scheduled a week out it was more disturbing. :)

Looking at this for 4.9.

**Comment by bummytime** [comment]
The fix for this: https://github.com/wordpress-mobile/WordPress-iOS/issues/3032 is causing the issue here.
