### ISSUE TITLE
Whitespace cleanup

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#500]
suppress all `&nbsp;`s

----
markup in app (4.6) and in wp-admin text: https://cloudup.com/cd10CoEJRpN

- when I add trailing whitespace, on the app, I get the non-breaking code space, whereas on the wp-admin text editor, I don't.

- in the app, extra returns/enters show as `<p><p/><p><p/><p><br></p>`... whereas on the text editor they come through as

`&nbsp;`

`&nbsp;`

`&nbsp;`

`&nbsp;`

**Comment by bummytime** [comment]
A couple of things... I have been experimenting with different approaches to suppress the ```&nbsp;``` including:

* Real time substitution
* Bulk removal/replace when the editor loses focus
* Bulk removal/replace when raw content is requested from the editor.

All of these things have strange side effects. The biggest one being the ```contenteditable``` node in ```UIWebView``` does not recognize trailing spaces that are not ```&nbsp;```. You can see this if you switch from the visual editor to the HTML editor and back again. Example:

https://cloudup.com/cTW7tPqGAz9

So...for 4.8, I am recommending we punt on this and regroup around what the best course of action is to handle spaces.

FWIW, looks like spaces give core issue too: https://core.trac.wordpress.org/ticket/26842 :-)

/cc @meremagee

**Comment by meremagee** [comment]
SGTM - the editor is stable at the moment and refactoring seems higher risk than necessary atm - For those preferring to edit html, they are more likely to be familiar with `&nbsp;`. Moving to 4.9.

**Comment by bummytime** [comment]
Note, we needed to be careful here because of this PR: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/581

**Comment by meremagee** [comment]
we now remove extra spacing entirely, consolidating any number of enter/returns to just 1 new paragraph. this has parity w/ io editor. :thumbsup:
