### ISSUE TITLE
Format bar icon overflow when display zoom is turned on

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#508]
The format bar is not looking so hot when display zoom is turned on.

![scaled screen_shot_2015-01-24_at_3_44_10_pm](https://cloud.githubusercontent.com/assets/154014/5889163/253d579a-a3e0-11e4-96f2-ae098bbb9660.png)

Unfortunately display zoom cannot be tested in the simulator...devices only. For reference: http://www.iphonehacks.com/2014/09/use-display-zoom-iphone-6-plus.html

/cc @meremagee

**Comment by meremagee** [comment]
On iPhone 6 - full icon list is not displayed & long blog names in header overlap icons: 
![](https://cloudup.com/iHSfuRaA-XV+)

**Comment by bummytime** [comment]
Closing this issue because it will be addressed in #708.
