### ISSUE TITLE
A post that failed to update will remain in the failed state even after the user updates the post through another medium

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#51]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/398

To recreate:
Edit a draft Post
Remove Internet connection
Save changes - Post fails to save (that's OK)
Restore Internet connection
Use the Dashboard view to edit the same Draft Post. Post saves OK.
Refreshing the Posts list doesn't remove the Failed Post update from the list even though it has now been superseded.

**Comment by diegoreymendez** [comment]
Could not reproduce this issue. I'm assuming this has been fixed since the ticket is really old.
