### ISSUE TITLE
Add auto-capitalization to appropriate fields

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Editor-iOS#522]
I noticed a few fields didn't have auto-capitalization enabled:
- Post content area
- Image caption
- Image description

iPad mini retina, iOS 8.1

**Comment by rachelmcr** [comment]
I confirmed that auto-capitalization is not enabled in:
- Image title
- Image caption
- Image alt text

The post content area does auto-capitalize now.

Tested in WPiOS 6.2.0.20160429 on iPhone 6, iOS 9.3.1
