### ISSUE TITLE
A blockquote can be added to list multiple times 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#530]
Unexpected behavior reported by a user:

> To replicate, tap the bullet list and then just keep tapping the quote icon.
>
> ![ns3wj-vmrb-900x900](https://cloud.githubusercontent.com/assets/154014/6034299/c3ad050c-abe6-11e4-963c-2f248d2f96f9.png)

**Comment by diegoreymendez** [comment]
Also - a blockquote can't be removed visually unless it's the closest parent format block.

**Comment by diegoreymendez** [comment]
Fixed.
