### ISSUE TITLE
block saving empty post on X/cancel

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#531]
remove "save draft" from cancel action sheet if no content has been added to the title nor body for consistency in app behavior (https://github.com/wordpress-mobile/WordPress-iOS/pull/2967)

![](https://cloudup.com/iL1ntMiBle9+)

repro:
- create post
- don't add any content to title nor body
- note that "post/save" is disabled when no content is added
- hit cancel/x
- note that "save draft" is an option in the action sheet
- hit "save draft"
- empty post is saved

**Comment by beaulebens** [comment]
I would propose that if we can detect that no content has been added/modified (and thus wouldn't prompt to Save Draft), that we shouldn't prompt anything, and that we should just leave the view. I find it annoying when I tap into the editor, then immediately tap out, to have to confirm my "unsaved changes" (of which there are none).

**Comment by meremagee** [comment]
> I would propose that if we can detect that no content has been added/modified (and thus wouldn't prompt to Save Draft), that we shouldn't prompt anything, and that we should just leave the view.

@beaulebens just came to note the same thing. The concern, of course, would be that it may be disorienting if a user accidentally hits X. Can be determined via user testing/user feedback however.

**Comment by meremagee** [comment]
needs a thorough look: https://lookback.io/watch/H3Yim6DAkf8gi9MzQ
- should not be able to "save" a draft of a completely empty post as noted
- upon opening the "failed" draft, should not see "unsaved changes: this post has local changes that were not saved. you can now save them or discard them" alert
- should not get options upon hitting X/cancel _again_ to "update draft" (or, really get the blocker at all)
- if hit discard, should not get follow-up alert about unsaved changes

**Comment by bummytime** [comment]
@meremagee 

> upon opening the "failed" draft, should not see "unsaved changes: this post has local changes that were not saved. you can now save them or discard them" alert

¿Por qué?

**Comment by meremagee** [comment]
_IF_ there is zero content in the post? If it's the case that we just _always_ save the local draft, then that is fine. If there is a way to see that the post has 0 contents, probably better not to save at all?

the crux of my logic is that we should never get into a state where a user can save an entirely empty draft because the process of discarding it seems to be increasingly friction-filled
