### ISSUE TITLE
Email: visual editor for iOS [WIP]

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#542]
Mailchimp
WP template: https://cloudup.com/c3zZyvS1nAx (we can add another/augment this one)
Img svg: https://cloudup.com/cUj6itrkwMx
Copy: tbd
CTA: >> itunes app store - dl/update app

cc @thianhlu

**Comment by meremagee** [comment]
@thianhlu - your thoughts much appreciated on who you'd like to receive the notice as audience will determine email content

- all users with the iOS app?
- all users who have not updated to 4.8 ~1wk after release?
- all users who will/should receive the new editor via update, install?

**Comment by thianhlu** [comment]
Lots of the copy you have for the blog post can be re-used here, its very concise and valuable info.

Lets do all users who not yet updated to 4.8 ~ 1wk after release. We would have one call to action which would bring them to itunes app store to upgrade. We will want to track clicks then ultimately upgrades just to see how these perform.

Extra bonus points if we can segment users like:
4.7
4.6
4.5
4.0-4.4
< 3.9

Might be interesting to see and tweak emails for those groups but no worries if its too complicated.

**Comment by meremagee** [comment]
> We will want to track clicks then ultimately upgrades just to see how these perform.

Clicks will be tracked in mailchimp. Looping in @sendhil as background so we can segment user list & get upgrades tracking in place.

**Comment by meremagee** [comment]
copy v1:

We’re thrilled to announce that latest release of WordPress for iOS includes a beautiful new visual editor. 

With the new editor, you can add rich text like **bold**, _italics_, [links](http://apps.wordpress.org), and lists naturally as you type. You can also insert images with a tap, seeing real-time uploading progress and images right in the post.

Update the WordPress app for iOS to try it out!

button: Update app now

we could create a gif or use the [onboarding img](https://cloudup.com/crPh5ETfgcM) somewhere for visual aide

**Comment by meremagee** [comment]
here's a basic basic basic draft (i'd update the footer since recipients would also be .org users):

![](https://cloudup.com/c2ddSBLorDT+)

advised by editorial, the current template and company voice doesn't lend itself well to really playful verbiage, but let me know what you think @thianhlu and we can take it in any other direction.

also, we're working with a professional animations contractor right now and as a trial he's working on a mobile visual editor animation since this release was timely and ads wanted to give him something to do (much better than me putting something jank together). should have the finished result ~next week. i think it would be a pretty great addition to a fairly stale, straightforward email. we could run an a/b with the animation and just text to see which performs better. or, we could move forward with a just-text email this week.

**Comment by thianhlu** [comment]
Few questions/comments:

- Email subject is "New Visual Editor"? Change this to something that is more descriptive and actionable. Something like "Update your WordPress mobile app"
- The copy seems almost too short. We aren't really saying anything compelling to give users a reason to update their app. Can we add back in some of your text from ^.
- Let's not use the term iOS in this email. Better to use iPhone.
- Email will need a graphic whether it be the animation you mentioned or the image we used in the onboarding. Big concern here is the image/gif should not be too large (file size wise).
- Width looks fine, just double check character count by line. Less than 70?
- Update app button is too wide. Max-width on that should be similar to width on the phone. 
- Is the template responsive? 
- Are we restricted to only this template? The header bar is quite tall and overwhelms the rest of the email. 
- Triple check that this isn't going out to anyone that has already updated the app, new users that already have it and that the list contains only unique emails.

**Comment by meremagee** [comment]
> Are we restricted to only this template?
Nope. we can do anything custom if you want that on your plate (looked through the MC ones but nothing jumped out as a good, clean option). I could also see what we've made in-house - where we send emails with a custom script, but I like the test options of mc more than winging it. The template as-is is pretty corporate and I couldn't balance the onboarding graphic in a lovely way, but I'll keep trying. I'll come up with more compelling language, too. 

> Triple check that this isn't going out to anyone that has already updated the app
We'll pull from current version lists which won't include anyone with 4.8 or higher. Won't pull until just before the email goes out.
