### ISSUE TITLE
Richtext + link leave format bar in weird state

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#563]
tested on iphone5s, ios7

Repro:
- type word
- select word
- style with b or i
- while word is still selected, hit link and make the word an anchor
- notice that b/i & link are left in a weird selected/not selected state until you change post state

![](https://cloudup.com/izehtYHcPKv+)

**Comment by meremagee** [comment]
seems to be triggered for any styles when something is hyperlinked, including the case where you don't have any richtext and simply link one word

**Comment by bummytime** [comment]
Closing. Not able to repro on latest internal with iOS9.
