### ISSUE TITLE
Previewing post on WP.com site with custom domain doesn't work (initially)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#570]
As reported by a user:

> I’ve found the following issue with previewing a saved draft:
>
1. Create a new post in app and save as a draft.
2. Load draft and tap preview icon — get an “Oops! That page can’t be found.” 404 error page in the preview instead of the post preview.
3. Go back to posts list and load a published post.
4. Tap preview icon — preview of published post works.
5. Go back to posts list and load draft post.
6. Tap preview icon — preview now works.
7. Quit app.
8. Relaunch app.
9. Load draft post.
10. Tap preview icon — get an “Oops! That page can’t be found.” 404 error page in the preview instead of the post preview.
>
> I can reproduce this consistently with saved drafts on my ZZZ.com site. I cannot reproduce this at all with saved drafts on my YYY.com site (which is normally private, but I tried setting it to public and it didn’t make a difference). Both sites are WordPress.com sites. The main difference I see is that ZZZ.com is using a custom domain.

Tested and verified. It seems like any .com site with a custom domain will encounter this same error.

**Comment by rachelmcr** [comment]
I re-tested this issue and can no longer reproduce it. On a WordPress.com site with a custom domain, I can preview a saved draft every time without any errors.

Tested on WPiOS 6.2.0.20160429 using iPhone 6, iOS 9.3.1
