### ISSUE TITLE
Img meta data - refined specs (caption)

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#574]
As discussed in slack, the contenteditable-false caption scenario could use a lookover. Currently, after setting a caption on an image, the cursor is restored within the caption area, and you can't breakout without tapping on the editable area. Since user can't edit caption inline, let's restore cursor to newline below caption/image after closing img settings page.

video: https://lookback.io/watch/YXXu24duZHjJq3CMp

cc @aerych

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/555
