### ISSUE TITLE
Disabled format bar buttons are confusing

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#575]
From a user:

> Using the new editor today, I typed the title and then tried to tap several times on the upload image icon, but couldn’t figure out why it wasn’t working and assumed this was a bug. After a few tries, I finally realized it was because I was still focused on the title field instead of the content area — but this wasn’t clear immediately since the disabled state doesn’t necessarily look disabled until you’ve seen it change to the enabled state.

We have received similar comments from others as well. We prolly could do one of two things:

1. Hide all format buttons (except HTML) when title field has focus
2. Change the color/opacity of the format bar buttons to something that screams "don't bother touching me" when the title field has focus

/cc @thianhlu @meremagee

**Comment by thianhlu** [comment]
Yup, lets make note and continue to compile all the feedback requests and then prioritize them. In this case we can do a few things like slide the toolbar back up when user goes to the post body.

**Comment by meremagee** [comment]
Will do. If this appears to be a trend, we could also experiment with allowing user to hit "media/img" icon while in title like they can with HTML (then set focus to body if it's on title and follow add media flow as usual)

**Comment by diegoreymendez** [comment]
We used not to show the toolbar when the user was typing the title, but that made it impossible to switch to HTML mode, since that's where the HTML mode button is.  That's the reason why the toolbar was shown even when the title was selected.

Just a bit of important background since we'll need to solve that issue if the toolbar is hidden.

**Comment by bummytime** [comment]
This has been addressed.
