### ISSUE TITLE
Conflict detection and resolution

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#58]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/404

When a post/page has been updated both in the server and the app, we don't do any conflict resolution and the changes in the app can get overwritten by the revision on the server
We should (easiest first):
Always give priority to the version in the app (changes overwritten in the server can be restored through revisions)
Alert the user of the conflict and offer a choice
Ideally allow the user to review the changes, but that seems like a complex UI for mobile

**Comment by aerych** [comment]
Since this issue is specific to a particular implementation of the editor this repo doesn't seem the best fit to wrangle the issue.  Closing and reopening 404.
