### ISSUE TITLE
Autocorrect not working when external keyboard is used 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#591]
Confirmed. From a user: 

> I'm using an iPad mini running the latest iOS. I am using an external keyboard. This is the exact same setup I had been using with the previous version of the app when the editor was HTML based. With the previous version, spellcheck functioned as expected, but since the update it doesn't matter what I type in the visual editor, nothing gets flagged for correction.

For ref, here are UIWebView's supported tags (but I am pretty sure some do not work in contenteditable divs...e.g. ```autocorrect```):

https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html

This may be a "can't fix" issue...

**Comment by rachelmcr** [comment]
This was also reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/3828 and in recent testing autocorrect worked as expected with an external keyboard. Closing as it works for me now.
