### ISSUE TITLE
Update bundle usage in sight of Cocoapods 0.36

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#593]
As reported by @sendhil in [this post](https://coreappso2.wordpress.com) we need to make sure our resources usage from pods will keep working for Cocoapods 0.36.

Refer to the post for more information.

**Comment by diegoreymendez** [comment]
FYI @bummytime, @meremagee

**Comment by bummytime** [comment]
already done.

**Comment by diegoreymendez** [comment]
:+1:
