### ISSUE TITLE
When a .org site is completely protected by basic auth, image upload doesn't work

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#594]
Title has it. All image uploads immediately fail:

![scaled screen shot 2015-03-04 at 12 39 06 pm](https://cloud.githubusercontent.com/assets/154014/6490387/7e1bc15e-c26b-11e4-8890-ecf476ebf628.png)

**Comment by meremagee** [comment]
still failing every time for me on ios7 and ios8 @SergioEstevao

**Comment by bummytime** [comment]
Just updating this with recent Slack conversation....this fix will land in WPiOS 5.1. Well test again on that internal.
