### ISSUE TITLE
UI/UX to show video insertion, upload and processing progress.

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Editor-iOS#602]
Add to the new visual editor the possibility to add videos to the post.

**Comment by SergioEstevao** [comment]
I add a first go on the UX of the video upload interface. I followed the same design as the image uploader. Don't mind the picker interface this is just the standard iOS interface for picking videos not the same we use on the application.

Here is a video of the interface in action:

https://cloudup.com/cBW47XGqBUx

Do you agree with this interface @bummytime @thianhlu ?

One thing that I took notice is that if we plan to do a meta edit option for video we will no be able to it the same way as the images because of the Play button that shows up in the middle of the video, in the same place we put the edit icon (pencil).

**Comment by thianhlu** [comment]
Looks really good @SergioEstevao 

Good point on the Edit icon. We could keep the video player looking like this 
![](https://cloudup.com/cqMQnOZPxPZ+)

and still have that same interaction?
cc @bummytime

**Comment by SergioEstevao** [comment]
Are you saying to just use the player bottom bar and drop the main play
icon on the Middle of the video? Do we keep that bar always visible? Do we
stop doing click to play in all the video frame?

And what we want to do when we click to edit the video? At the moment
wpadmin doesn't do anything...

**Comment by SergioEstevao** [comment]
After discussing with @thianhlu we decided that at the moment we will only have video insert and upload UI, edit of meta options will be done in the future and addressed in a different issue.

The standard UI for media controls will be used.

**Comment by SergioEstevao** [comment]
@thianhlu we need some ui/ux to show as a video placeholder when we still finding or processing a video element. This could happen for example when we open a post with wpvideo shortcode and it can take a while to get the video url of the video. It can also after the upload when we switch from the local url to the remote urls.

**Comment by thianhlu** [comment]
@SergioEstevao It would be cool if we can always display a frame from the video on the UI and reuse the same UI as `failed`, `uploading`. Using a dashicon in this example.

![](https://cloudup.com/cVlAyg7AfNi+)

**Comment by thianhlu** [comment]
In the case we dont have a frame we can display gray BG with the message above

**Comment by thianhlu** [comment]
Using the wp dark gray

![](https://cloudup.com/cw-2bv7iB1W+)

**Comment by thianhlu** [comment]
If you prefer something more lightweight, we were going to do something like #293 which is nice when we have no idea how big it will be or if we want it to be less prominent on the UI.

**Comment by SergioEstevao** [comment]
Are you planning an image or SVG?

**Comment by thianhlu** [comment]
I can do either. Want me to do vector in PDF or SVG?

**Comment by thianhlu** [comment]
Chatted with @drw158 and he may have some bandwidth for a better icon. 

Otherwise we will use dashicon here, https://github.com/melchoyce/dashicons/blob/master/svg/format-video.svg

**Comment by SergioEstevao** [comment]
SVG like we did for retry and please send me the color reference

**Comment by thianhlu** [comment]
WP Gray Dark
#2e4453

**Comment by thianhlu** [comment]
@drw158 maybe something like this?
![](https://cloudup.com/cZChShDo1VQ+)

**Comment by drw158** [comment]
Here are some options with the new photo icons included (2nd row) for reference:

![screen shot 2015-04-01 at 4 05 33 pm](https://cloud.githubusercontent.com/assets/618551/6953241/a61230e8-d88d-11e4-85e3-b0fa4121dca5.png)

I prefer 3 or 4

**Comment by drw158** [comment]
Here is the svg for No. 4:

https://cloudup.com/cjzt9g8Wt-z
