### ISSUE TITLE
Text pasted from notes.app into the visual editor does not save

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#603]
Users have reported that when pasting text from notes.app into the visual editor, the text appears but when they publish the post none of the pasted text is uploaded (same for saving a draft). If they post the text into the HTML editor instead, everything works as expected. 

I was able to repro this issue both on the WPiOS app store 4.8.1 as well as WPiOS 5.0 internal: 

https://cloudup.com/ccbbRC1VTEI

/cc @meremagee

**Comment by meremagee** [comment]
Looks like @aerych had some hints as to how to fix: https://ios.forums.wordpress.org/topic/saving-does-not-load-latest-changes-into-app?replies=4#post-13535

**Comment by meremagee** [comment]
Let's look into sanitizing paste from other apps in visual editor

**Comment by meremagee** [comment]
Pasting from safari (tested lipsum.com content) adds spans/styling as well
