### ISSUE TITLE
Fail gracefully when a user attempts to upload invalid media

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#609]
From a user: 

> Earlier today, I tried to make a post and insert a tiff image file into it. I was not able to upload it, but I didn’t get a message explaining why (the reason being that it’s not an allowed type on WordPress.com). I can imagine how a less-savvy user might try uploading non-allowed files many times and not understand what’s going wrong.
>
> Here’s what happens when trying to upload a tiff file:
>
>Step 1: uploading
> ![img_3054](https://cloud.githubusercontent.com/assets/154014/6943247/5cd2ff4c-d852-11e4-8090-b2b75b0bc06d.png)
>
> Step 2: upload fails
> ![img_3056](https://cloud.githubusercontent.com/assets/154014/6943253/6863f06e-d852-11e4-8888-b082067746f3.png)
>
> The button to retry the upload works when I click it, but of course the upload fails again.
>
> I think it would be better if the failed image showed a message that this filetype can’t be uploaded, instead of letting the user try again.

**Comment by SergioEstevao** [comment]
I tested this a bit and found a way to know what are the available formats on the site and how to convert the images to one of them. 

So now we have to decide how to present this to the user:

 1. Show a message to the user that the file is in an invalid format when he selects it to add to the post.
 2. Show a message that there is a issue with the file format and ask if we can convert it to another format (JPG) before uploaded it.
 3. Convert it automatically and don't ask anything to the user

cc @bummytime @thianhlu

**Comment by bummytime** [comment]
@SergioEstevao my vote would definitely be for either 2 or 3. I like 3 in that we just take care of it for the user. However, I am wondering it the type of user that would try to upload a TIFF (or whatever uncommon format) would be upset if we convert their file without warning.

If you held a :gun: to my head, I would say let's go with option 3.

**Comment by meremagee** [comment]
> If you held a :gun: to my head, I would say let's go with option 3

We can update the app FAQ so that happiness engineers have a reference for directing any users who want more info

**Comment by SergioEstevao** [comment]
Ok I will do 3, I will convert automatically and for lossless formats like TIFF I will convert to PNG that is also lossless.

**Comment by SergioEstevao** [comment]
This issue is solved, any unsupported image file formatted is now converted to jpg automatically.
