### ISSUE TITLE
Media upload spinner still displays after media is removed

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#627]
When uploading media, if you try to delete a video/image by backspacing over it, the nav bar "uploading" progress bar still displays: https://cloudup.com/cBmDmgY8RAD

I am assuming the media is actually still being uploaded, so we should also consider if the upload should be killed (if possible).

Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/3503

**Comment by rachelmcr** [comment]
I confirmed that this is still an issue as of beta app v. 6.1.0.20160331. If I tap on the "uploading" progress bar or the uploading image directly, I can stop the upload, but if I simply backspace over it the uploading progress bar keeps going and the image uploads to the media library. I also expected the image upload to be canceled, if possible.
