### ISSUE TITLE
Blockquote on empty post

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#629]
Can't add blockquote if post content is empty (tested zoom and non-zoom, ios8)
- create new post
- focus cursor in body
- tap quote
- can't select quote

**Comment by bummytime** [comment]
@meremagee is this bug about the inability to select a blockquote or the fact you cannot make one at all? If it's the latter, it will be fixed here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/622

**Comment by meremagee** [comment]
Can't make one if post is empty - because it won't select if the post is empty, so both. I'll keep my eye on #622 - didn't see this issue listed.

**Comment by bummytime** [comment]
Looks like this is fixed. Tested in latest internal.

**Comment by meremagee** [comment]
:+1:
