### ISSUE TITLE
Backspace breaks uploads

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#643]
Video of the issue [here](https://lookback.io/watch/xLJENJzYQEhaCZted).

*Steps to reproduce:*
- Upload a video in the editor
- Make sure the caret is placed right after the video as it is uploading.
- Press backspace.

*Expected behaviour:* the upload should be cancelled.
*Current behaviour:* Can't close the post, the "Uploading..." message is still shown.

**Comment by bummytime** [comment]
@SergioEstevao do you think this could get fixed for 5.1?
