### ISSUE TITLE
Publish and settings buttons too close

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#653]
From a user:
> The Publish button and the Post Settings button are way too close together in @WordPressiOS. Always accidentally publishing drafts

We have heard this more than once since the new editor was released.

/cc @thianhlu

**Comment by thianhlu** [comment]
K on it.

**Comment by thianhlu** [comment]
![](https://cloudup.com/csB3w2i772S+)

@bummytime thoughts?

Im gonna redo our icons on 44*44.

**Comment by bummytime** [comment]
Looks good @thianhlu. Prolly can take care of https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/640 as well in this issue.

**Comment by thianhlu** [comment]
@bummytime it appears it was just the X and chevron back icon are on 30*30. Do you want this on 44*44?

**Comment by bummytime** [comment]
Sure @thianhlu

**Comment by thianhlu** [comment]
@bummytime updated icons on 44*44
https://cloudup.com/cu1cPa1nJZ4
