### ISSUE TITLE
Copy and pasting of media

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#655]
A user requested the ability to copy and paste media from within the visual editor.

See: https://lookback.io/watch/8hyTmSb4oiP9jNu2e

/cc @SergioEstevao

**Comment by bummytime** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/4815

**Comment by SergioEstevao** [comment]
Solved by #789
