### ISSUE TITLE
Disabled toolbar and buttons (updated design)

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#657]
- background-color: rbga(#f3f6f8, 0.5) - (Gray Light)
- color: #e9eff3 - (Gray Lighten 30)
- border-top: #a8bece - (Gray Lighten 10) *Also same color for the line separator

**Comment by thianhlu** [comment]
Re: disabled state. So right now the lightest Gray we have in the style guide we have is Gray Light.

Option 1:
- background-color: Gray Light
- color: Gray Lighten 30
![](https://cloudup.com/cGn_IvZYV7T+)
* Too light and not enough contrast

Option 2:
- background-color: Gray Light
- color: Gray Lighten 20
![](https://cloudup.com/cjiyjc8IEa9+)
* Too much contrast, no longer looks disabled

Option 3:
- background-color: Gray Light at 0.5 opacity
- color: Gray Lighten 30
![](https://cloudup.com/c9TZmqbyEfE+)
* Strikes the best balance but not "officially" part of style guide since its a derivative of Gray Light. This is by far the best route to go. Use hex #F9FBFC so content doesn't bleed under.

cc @bummytime

**Comment by bummytime** [comment]
Sounds great @thianhlu !
