### ISSUE TITLE
Default toolbar and buttons (updated design)

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#658]
![](https://cloudup.com/cGEYT7HEN7l+)
![](https://cloudup.com/cTwAvWxyYv1+)

- background-color: rbga(#f3f6f8, 0.5) - (Gray Light)
- color: #a8bece - (Gray Lighten 10)
- border-top: #a8bece - (Gray Lighten 10) *Also same color for the line separator

**Comment by bummytime** [comment]
Note: because of alpha channel issues with the UIToolbars + input accessory view we are holding off on implementing the chevron divider above.

**Comment by thianhlu** [comment]
@bummytime A few notes for this one:

- Let's increase the height of the separator/divider to 34
- We can leave the chevron out for now and break out into a separate issue. We will still try and implement this on the Android side of things.
- Are we using the icon for the HTML button? We prob had a reason I'm forgetting.

**Comment by thianhlu** [comment]
Closing @bummytime took care of all the issues

**Comment by bummytime** [comment]
@thianhlu I made issues for your points above: #679 & #680
