### ISSUE TITLE
Animate format bar selection (updated design)

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#660]
Example: https://cloudup.com/cb2NTJ_8DxQ

**Comment by bummytime** [comment]
@thianhlu there may be an issue with the circular animation in the format bar. See: 

![screen shot 2015-06-25 at 11 05 02 am](https://cloud.githubusercontent.com/assets/154014/8359128/20718756-1b2a-11e5-98a0-3caef92f6884.png)

Since the toolbar buttons are square, portions of the animation will be clipped.

**Comment by thianhlu** [comment]
Can you upload a video? The animation fades out near the edges so maybe it wont be a big issue.

**Comment by bummytime** [comment]
@thianhlu Still working out the exact animation imp...video will come shortly. However I think you can see the issue when you scrub the sample animation video above:

![napkin 10 06-25-15 3 48 03 pm](https://cloud.githubusercontent.com/assets/154014/8365297/c62661f4-1b51-11e5-9845-628aac6856e0.png)

...the initial outer circle is huge and overlaps neighboring icons.

**Comment by bummytime** [comment]
@thianhlu here is a quick video of just the outer ring animation: 

https://cloudup.com/cHhbipOw1Qy

This is basically as big as I can go with that ring without clipping.

**Comment by bummytime** [comment]
@thianhlu Here is another rough cut of the animation now with an inner circle that scales out and fades (initial color is still black):

https://cloudup.com/cvNo0uRdB-K 

Lots of levers we can pull here. :-)

**Comment by bummytime** [comment]
@thianhlu Last update tonight :-)

https://cloudup.com/ckvuNErkNu2

**Comment by thianhlu** [comment]
Changes look really great @bummytime. This is good to go. Thanks!
