### ISSUE TITLE
When using as embedded framework, nothing appears

### ISSUE THREAD

**Issue by Spacelapp** [wordpress-mobile/WordPress-Editor-iOS#664]
Looks like not all [NSBundle mainBundle] are replaced with [NSBundle bundleForClass:[self class]].

**Comment by bummytime** [comment]
@Spacelapp I'm assuming you are referring to this [line](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/3d0b1ca3ace76aa9a062e52b716440b27cb0bbd8/Example/EditorDemo/WPViewController.m#L76) in the example app?

**Comment by Spacelapp** [comment]
@bummytime no, when I install WordPress-Editor via Cocoapods (pod 'WordPress-iOS-Editor') I got these lines of code in WPEditorView:
- (NSString*)editorRawHTML
{
    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"editor" ofType:@"html"];
    NSData *fileContentData = [NSData dataWithContentsOfFile:filePath];
    NSString *fileContentString = [[NSString alloc] initWithData:fileContentData encoding:NSUTF8StringEncoding];
    
    return fileContentString;
}

**Comment by bummytime** [comment]
@Spacelapp It looks like you are using an earlier pod version v0.6 or older. In the latest editor pod (v0.7) that code no longer exists.

**Comment by Spacelapp** [comment]
@bummytime yeah, but why when I integrate it with pod 'WordPress-iOS-Editor' ?

**Comment by bummytime** [comment]
@Spacelapp I would suspect it is something in your local environment. Perhaps try deleting the `Podfile.lock` file and `Pods` directory and running `pod install` again or specifying the version number in your podFile...e.g. `pod 'WordPress-iOS-Editor', '0.7'`
