### ISSUE TITLE
When editor initializes it steals keyboard from other controls

### ISSUE THREAD

**Issue by teemobean** [wordpress-mobile/WordPress-Editor-iOS#667]
I'm trying to build a custom blog app which leverages the editor. I put the editor on a view controller with other controls successfully. However, when the editor loads, it steals keyboard focus from other controls (which loaded quicker than the editor). Is there a way to configure the editor to not steal the keyboard focus? I tried looking at the obvious things but couldn't find a way to do it.

**Comment by bummytime** [comment]
@teemobean You could try setting `self.editing = NO;` in the `viewDidLoad` method of your class that subs `WPEditorViewController`. Then when you are ready to beginning editing, you can call `startEditing`.

The title field actually gains focus in JavaScript [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/9812b6c9a699cd654ef5c0cffe9bed9f91c06782/Assets/ZSSRichTextEditor.js#L2629).

**Comment by teemobean** [comment]
@bummytime Hi - thanks! That worked like a charm. I ended up updating the javascript to not take the focus, as there wasn't another good mechanism to call `startEditing` in my app. Thank you for your help!

**Comment by bummytime** [comment]
Great to hear @teemobean!
