### ISSUE TITLE
Link Button icon is cropped or out of screen

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Editor-iOS#683]
I noticed this on the demo app:

iPhone 6

<img width="374" alt="screen shot 2015-07-03 at 10 25 09" src="https://cloud.githubusercontent.com/assets/651601/8491567/fa246772-216d-11e5-9804-5d8a84b53d5c.png">

iPhone 4s
<img width="320" alt="screen shot 2015-07-03 at 10 24 40" src="https://cloud.githubusercontent.com/assets/651601/8491572/02c38868-216e-11e5-8258-267cc91662ec.png">

**Comment by bummytime** [comment]
The cropped link icon is by design with the updates from #675. @thianhlu increased the size of the icons themselves and the format bar now will scroll on any phone except the 6+. We are going to introduce another tooltip to point out the bar scrolls fwiw: #676

**Comment by bummytime** [comment]
Reopening this because @SergioEstevao noted some trouble scrolling the format bar on the 4s.

**Comment by thianhlu** [comment]
@bummytime @SergioEstevao One thing to note is if we determine that we can't implement the chevron, we might have to introduce a slight drop shadow to help the user understand the depth (in addition to the onboarding). I do want to keep the icons at 44*44 to keep inline with iOS touch target sizes but perhaps we can save some space by remove some padding from left button and some padding on the HTML button. Just a thought.

**Comment by bummytime** [comment]
I like the idea of the drop shadow @thianhlu, but unfortunately, we are going to run into the same alpha issue as the chevron: #680. :iphone: :gun:

**Comment by bummytime** [comment]
Should be fixed now.
