### ISSUE TITLE
Unable to select all content in the Editor

### ISSUE THREAD

**Issue by barathank** [wordpress-mobile/WordPress-Editor-iOS#697]
First of all, great effort on this control.

I am using this control and trying to select the content of the Editorview but i am only able to manually select content upto a point where it does not need scrolling. Once i try to scroll down the page to continue on the selection process the start scroll stays in the place but the end scroll goes back to the top of the page near by to the selection start. Please advise.

**Comment by bummytime** [comment]
Tried to repro on iOS 9 and could not *except* when there was media below the fold. Because of this I am closing this issue in favor of #422. 

Thanks for the report @barathank!
