### ISSUE TITLE
Very Thanks this code!!

### ISSUE THREAD

**Issue by RobinChao** [wordpress-mobile/WordPress-Editor-iOS#704]
Very Thanks this code!!  that's help me solve something.

Did this Editor can add  html tag   'iFrame'  or  'embed' ?

or did this can add some custom html zone to editor ?

very thanks  again.

**Comment by bummytime** [comment]
Thanks @RobinChao! 

If I am understanding your question correctly, you are asking if it's possible to have the editor add custom HTML to to the format bar so the user can insert it by pressing a button. Unfortunately there is no built-in way to do this, however you could fork the editor and write the code yourself. Take a look at this:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/1b614724fbc005be4346c7870498658c8b537267/Classes/WPEditorView.m#L1772-L1976

when a format button is pressed, it calls into JS and one of these functions is subsequently executed:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/1b614724fbc005be4346c7870498658c8b537267/Assets/ZSSRichTextEditor.js#L346-L554

which adds the tag to your editor document. So to insert custom HTML, you would have to create a new function in JS that does what what you need, and then create a function that wraps it in Obj-C. 

Hope this helps!

**Comment by RobinChao** [comment]
very  thanks.  i will try.

**Comment by michaelmou** [comment]
I had try it use "document.execCommand('insertiframe', false, html);"
But , It didn't work.

**Comment by michaelmou** [comment]
ZSSEditor.insertHTML = function(html) {

    var currentField = this.getFocusedField();

    if (currentField.isMultiline()) {
        // When inserting HTML in the editor (like media), we must make sure the caret is wrapped in a
        // paragraph tag.  By forcing to have all content inside paragraphs we obtain a behavior that's
        // much closer to the one we have in our web editor.
        //
        currentField.wrapCaretInParagraphIfNecessary();
    }
	document.execCommand('insertHTML', false, html);
//    document.execCommand('insertiframe', false, html);
//    ActiveDocument.execCommand("insertiframe", false, html);
	this.sendEnabledStyles();
};
