### ISSUE TITLE
Lose keyboard in HTML mode when image button is pressed

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#706]
To Repro:

1) Create new post
2) add some text to the body
3) switch to HTML mode. 
4) Press add media button. 
5) It throws error and keyboard is dismissed (expected) however you cant get it back (not expected)

**Comment by diegoreymendez** [comment]
Closing this, as an alert message is now being displayed when clicking on this button in HTML mode.

/cc @bummytime
