### ISSUE TITLE
Editor does not work with iPad multitasking in iOS9

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#708]
The editor is belly up when used within iPad multitasking in iOS 9:

![editor - make bigger](https://cloud.githubusercontent.com/assets/154014/9548943/0033634e-4d69-11e5-9aa9-1989de0e52f0.png)

![editor - slide in](https://cloud.githubusercontent.com/assets/154014/9548945/0037f2b0-4d69-11e5-9882-bdd25ea18bac.png)

![editor - split](https://cloud.githubusercontent.com/assets/154014/9548944/0035947a-4d69-11e5-9b19-5f76b5b70ea7.png)

/cc @thianhlu

**Comment by thianhlu** [comment]
Lets come up with a complete list of all the fixes and features we will want/need to support

**Comment by bummytime** [comment]
Word.

/cc @meremagee

**Comment by bummytime** [comment]
Just a few more images showing the editor in as the primary app with soft keyboard:

**Slide over:**

![screen shot 2015-09-02 at 12 55 33 pm](https://cloud.githubusercontent.com/assets/154014/9639608/7cdee500-5172-11e5-8e42-ad688e0bdf82.png)

**Split view (1 third):**

![screen shot 2015-09-02 at 12 54 37 pm](https://cloud.githubusercontent.com/assets/154014/9639603/794f45c4-5172-11e5-8d06-55276871b22e.png)

**Split view (middle):**

![screen shot 2015-09-02 at 12 56 00 pm](https://cloud.githubusercontent.com/assets/154014/9639669/c186da5a-5172-11e5-9e93-4c33c2d21078.png)

It seems like the most logical course of action (at least as a 1st step) is to refactor any logic that is explicitly driven by specific devices or orientation. In its place, we can take advantage of the size classes and trait collections that Apple recommends. 

![multitasking-size-classes_2x](https://cloud.githubusercontent.com/assets/154014/9639836/a81eaaf6-5173-11e5-924c-82e46fe248df.png)

So in our situation, that would mean switching to the iPhone (aka compact) format bar and the iPad bar (aka Regular) when appropriate.

Also, we should see if it is possible to leverage autolayout in the input accessory view so the padding between format icons can be adjusted automagically:

<img width="593" alt="napkin 14 09-02-15 1 15 15 pm" src="https://cloud.githubusercontent.com/assets/154014/9640004/af89856c-5174-11e5-838d-ed71ac930607.png">

@thianhlu I am going to explore these ideas and let you know what I come up with.

**Comment by thianhlu** [comment]
sounds good bummy. so with autolayout we should define the min/max of each button and button grouping, as well as what happens when we go below a min width for the entire format bar (horizontal scroll, sub menu, etc) so it works on every ios device

**Comment by bummytime** [comment]
Leaving an update here from an offline conversation. We have decided to use the current iPhone style format bar for the compact size and the current iPad format bar for the regular size:

<img width="743" alt="napkin 15 09-04-15 2 43 03 pm" src="https://cloud.githubusercontent.com/assets/154014/9693118/7d64aec2-5313-11e5-972b-c17541a091aa.png">
