### ISSUE TITLE
Location UI glitches on failure

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#71]
Original Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1970

**Comment by rachelmcr** [comment]
Are there other likely sources of failure for the location UI (since https://github.com/wordpress-mobile/WordPress-iOS/issues/1969 was fixed)? If not, I'm inclined to close this issue since there haven't been any recent reports of UI glitches like this.
