### ISSUE TITLE
Could not build module 'WordPress_iOS_Shared'

### ISSUE THREAD

**Issue by zzStar** [wordpress-mobile/WordPress-Editor-iOS#710]
There are two issues when I build with XCode6 

1. WPAnimatedImageResponseSerializer.h:1:9:
Include of non-modular header inside framework module 'WordPress_iOS_Shared.WPAnimatedImageResponseSerializer'

2. WPEditorToolbarView.m:2:9: Could not build module 'WordPress_iOS_Shared'
![image](https://cloud.githubusercontent.com/assets/7801496/9572507/1c74af0a-4fe3-11e5-85e3-4b014ff09995.png)

**Comment by sendhil** [comment]
See my comment over at https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/709#issuecomment-136606339

**Comment by bummytime** [comment]
Closing this issue in favor of #709
