### ISSUE TITLE
Bug - Multi tasking format bar layout issues

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#718]
https://cloudup.com/criGmEHpd45

1) Landscape where we had split screen and dismissed window on the right. 
2) Landscape and 50-50 split

**Comment by bummytime** [comment]
@thianhlu Is this on device or the sim? Is there a reliable way to repro?

**Comment by thianhlu** [comment]
Device. So pretty straight forward for both.

1) Open up demo in portrait -> switch to landscape -> start editing -> add new split window (any app) -> toggle back to editor, type some stuff -> dismiss split window by dragging to the right. 

2) Open up  Open up demo in portrait -> switch to landscape -> start editing -> add new split window (any app) to 50% of the screen

**Comment by thianhlu** [comment]
videos here:
https://cloudup.com/c65SGxL9zRX

**Comment by bummytime** [comment]
Tested this in `develop` on WPiOS — looks like the issue may not be occurring over there.

https://cloudup.com/cPZAPiVa1dP

**Comment by bummytime** [comment]
@thianhlu I am going to close this issue for right now since this will be addressed in #708.
