### ISSUE TITLE
Link Modal - Improving UX

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#722]
After inserting a link, linked word(s) remain selected by editor. We should be losing focus on that word and have the cursor directly to the right of the word after linking.

current:
![](https://cloudup.com/cadyyZrOQCi+)

**Comment by diegoreymendez** [comment]
@rachelmcr - I think this would be OK when inserting both the link and the link name from scratch.

However if the user double taps on an existing word to add a link, closing the dialogue should probably maintain the previous selection.  Thoughts?
