### ISSUE TITLE
Undo function is not working

### ISSUE THREAD

**Issue by hammyhamza** [wordpress-mobile/WordPress-Editor-iOS#726]

**Comment by bummytime** [comment]
Thanks for reporting this @hammyhamza.  I am closing this issue since this feature request is captured in #496 .

**Comment by hammyhamza** [comment]
But  both **UNDO** and **REDO** are still not working

**Comment by bummytime** [comment]
@hammyhamza, pull requests are welcome. ;-)

**Comment by xineason** [comment]
But both UNDO and REDO are still not working

**Comment by xineason** [comment]
@hammyhamza  did you fixed it?

**Comment by hammyhamza** [comment]
No i managed some workaround

**Comment by iosyaowei** [comment]
both UNDO and REDO are still not working， how do  ???
