### ISSUE TITLE
Bug with bold button

### ISSUE THREAD

**Issue by hammyhamza** [wordpress-mobile/WordPress-Editor-iOS#729]
If there is no text in editor **BOLD** button doesn't work

**Comment by bummytime** [comment]
Thanks for reporting this @hammyhamza. I am not sure if I am following you here. Pressing the bold button and then typing text seems to work on in the EditorDemo. Could you provide specific steps to repro?

**Comment by hammyhamza** [comment]
I can reproduce this issue for bold and italic.
Remove all the text in the editor now enable bold / italic and try to type. 

Same issue occurs in **Wordpress iOS Application**

**Comment by bummytime** [comment]
@hammyhamza I am going to close this bug in favor of #411. Thanks!
