### ISSUE TITLE
Add Search to Site Picker in Editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#739]
A user requested the ability to search the sites in the site picker dropdown in the editor, similar to the search in My Sites. (Currently, there is no site search, so you have to scroll through all of your sites to select one.)

Example from My Sites site picker:

![my sites - site picker search](https://cloud.githubusercontent.com/assets/8658164/11091344/73a84eaa-8871-11e5-9cb0-e105a19f29df.png)

![my sites - site picker search 2](https://cloud.githubusercontent.com/assets/8658164/11091345/7723b1fa-8871-11e5-9b1a-e7a1a89d7c9c.png)

Related issue for Notifications site search: https://github.com/wordpress-mobile/WordPress-iOS/issues/4300

**Comment by jleandroperez** [comment]
Closing this one since we already have a Search implemented in the site picker.

Thanks Rachel!
