### ISSUE TITLE
Bold and italic format buttons don't work when editor is empty

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#741]
If there is no post content in the editor yet, selecting the bold or italic formatting buttons has no effect. As you start typing, the text has no formatting and the button is deselected.

To reproduce:
1. Start a new post in the editor
2. Before adding any text, tap the bold or italic button
3. Start typing
Result: The text has no formatting.

If there is some text in the editor, tapping one of those formatting buttons results in the text you type afterwards being formatted as expected.

Moved report from https://github.com/wordpress-mobile/WordPress-iOS/issues/4191

**Comment by bummytime** [comment]
After an offline convo, @rachelmcr and I agreed to close this issue in favor of #411.
