### ISSUE TITLE
Featured images: App allows you to record a video, then crashes

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#749]
When setting a featured image, the app allows you to choose the live camera option and record a video. (That should not be allowed for featured images.) When you try to use it, however, the app crashes.

Steps to reproduce:
1. Start a new post on a site that supports featured images.
2. Tap gear icon.
3. Tap Set Featured Image.
4. Choose the live camera option.
5. Switch to video.
6. Record a tiny video.
7. Hit Use Video.
8. The app returns to the image picker for a second before crashing.

/hat tip to Adam for the report.

**Comment by SergioEstevao** [comment]
Excellent catch @rachelmcr!  I will fix this.

**Comment by sendhil** [comment]
Closing as per https://github.com/wordpress-mobile/WordPress-iOS/issues/4519 and https://github.com/wordpress-mobile/MediaPicker-iOS/issues/91
