### ISSUE TITLE
Images uploaded via the app are missing edit fields in web admin.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Editor-iOS#752]
Reported in the forums: https://ios.forums.wordpress.org/topic/photo-link-to-attachment-page?replies=3
Under Display Settings, the `Size` field is absent, and the `Edit Original` and `Replace` buttons are missing from below the image preview. 

Example of an image uploaded via the app: http://www.ourbook.me/wp-content/uploads/2015/12/upload_iOS.png
![upload_ios](https://cloud.githubusercontent.com/assets/1435271/11655025/ee2b7018-9d6f-11e5-9e24-1b95e5aa7df0.png)

Example of an image uploaded via the browser: http://www.ourbook.me/wp-content/uploads/2015/12/upload_browser.png
![upload_browser](https://cloud.githubusercontent.com/assets/1435271/11655026/f30d0830-9d6f-11e5-83b9-966f3724a6c0.png)

**Comment by rawzone** [comment]
We encounter this problem as well...

Not only are the fields missing in the editor, but the output of the image markup is also missing the new (Wordpress 4.4) responsive code (srcset etc).

**Comment by aerych** [comment]
Looks like adding/updating the `class` attribute and specifying one for `wp-image-___` where the `___` is the attachment ID should fix the issue with the missing fields.

**Comment by aerych** [comment]
> but the output of the image markup is also missing the new (Wordpress 4.4) responsive code (srcset etc).

@rawzone Is that baked into core now or still a plugin? I've just tried inserting an image into a post via the web wp-admin but I'm not seeing the `srcset` attribute added.  I've tried on an install of 4.4 and on the latest nightly build.   Am I missing a step?

**Comment by rawzone** [comment]
@aerych This is indeed build in to Wordpress 4.4. I tried to setup a fresh Wordpress 4.4 and added a image to a test post. And sure thing, image output is using the new responsive markup. (srcset, sizes etc).

I've done this testing in a brand new Wordpress 4.4 install with the Twenty Fifteen theme.
See this [screenshot](http://i.imgur.com/kr0FJbj.png)

**Comment by aerych** [comment]
@rawzone Thanks for the follow up.  It looks like I have something wonky with my test sites I need to sort out.

**Comment by rawzone** [comment]
@aerych No problems. Should you need any further information, please do not hesitate to contact me

**Comment by aerych** [comment]
> Looks like adding/updating the class attribute and specifying one for wp-image-___ where the ___ is the attachment ID should fix the issue with the missing fields.

Potentially related issue with thumbnails: https://ios.forums.wordpress.org/topic/the-change-of-jpg-to-jpeg-causing-plugins-to-fail?replies=9#post-14506
