### ISSUE TITLE
Editing an image and selecting a size doesn't seem to change the post

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#755]
Steps to recreate:
1. Created a new post with a large image.
2. Tap the image to show the edit control. 
3. Tap edit.
4. Change the size to something other than full. Dismiss the edit window.
5. Scroll around to make the Update button turn on.
6. Update the post.
7. View the post and see the image size hasn't changed.

**Comment by rachelmcr** [comment]
Could this be related to https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/752?

**Comment by aerych** [comment]
Totally related :)  Closing as a dup.  Nice catch @rachelmcr
