### ISSUE TITLE
Small code error in ZSSRichtTextEditor.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#759]
[This line](https://github.com/wordpress-mobile/WordPress-Editor-iOS/commit/9bffbe35851238c360f2e1d242266f6c5646c117#diff-79afd987f3d5e19bd3ae660053a42906R2244) should return `null` instead of `nil`.

**Comment by diegoreymendez** [comment]
This issue is an error and should be in a different repo.

**Comment by SergioEstevao** [comment]
:shipit:
