### ISSUE TITLE
Changing views makes placeholder text disappear

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#791]
Changing the view (e.g. by opening the site picker or post settings) and then returning to the editor view makes the placeholder text disappear from whatever field is in focus.

Steps to reproduce:

1. Open the editor to start a new post
2. With the title field in focus, open the site picker
3. Go back to the editor. Result: The "Post Title" placeholder text is gone.
4. Tap into the body of the post, so it's in focus
5. Open the post settings
6. Go back to the editor. Result: The "Share your story here..." placeholder text is gone.

Tested on iPhone 6, iOS 9.2.1, app beta 6.1.0.20160318.

**Comment by SergioEstevao** [comment]
Should be fixed on the next 6.1 release.

**Comment by rachelmcr** [comment]
I confirmed this is fixed (confirmed in 6.3 beta); closing the issue.
