### ISSUE TITLE
Insertion of video on pages without any content fails

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Editor-iOS#797]
Expected behaviour:

- On a brand new post or one without any content.
- Click to insert media and select a video
- A video thumbnail should be show while the upload/progress is happening
- A video should be show on the end.

Actual behaviour:

-Nothing is show after selecting the video

How to Test:

- On the simulator you can drag and drop a video to the simulator to have a video in the Camera Roll
- The do the steps described on the Expected behaviour.
- Check also behaviour on post with content, by adding in the start, middle and end of the post.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Check out [this video](https://cloudup.com/cPuc_OsUu5p).  The two big issues I'm seeing is.

- If the video is the first thing you add, you can't type before it.
- There's a caret coming up right in the middle of the video.
