### ISSUE TITLE
Pasting text results in some weird HTML code that causes typing issues in visual mode.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#803]
Related report: https://twitter.com/chartier/status/719904887119544320

We're seeing some strange behavior of the visual editor after text is pasted into it.  It seems like something's causing unwanted HTML tags to be added to the pasted text.

One example is `<p><br/></p>` sequences.

I'll add more info here as I investigate this issue.

**Comment by diegoreymendez** [comment]
It seems even a simple `<br>` will cause this behavior.  I've tested this by bypassing `wp.saveText` from [this line](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L2739) and `wp.loadText` from [this line](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L2758), so I can edit any HTML code from the HTML editor (and make sure the HTML is maintained when switching to visual mode).

**Comment by diegoreymendez** [comment]
Commenting all the code in [this method](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L2447) fixes the issue, so it's clearly in our end.

**Comment by astralbodies** [comment]
@diegoreymendez This fix will be in WPiOS 6.2 most likely, right?

**Comment by diegoreymendez** [comment]
@astralbodies - This is [already merged into WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/5137), for a 6.2 release indeed.
