### ISSUE TITLE
Enter text auto break to newline .

### ISSUE THREAD

**Issue by viettrungphan** [wordpress-mobile/WordPress-Editor-iOS#808]
Step to reproduce:
1. Go to iPhone keyboard setting, add language Vietnamese.
2. On WPE, switch to edit mode.
3. Switch keyboard to Vietnamese.
4. Press on A and A one more time you will get Â character.
5. Press another character such as A.
Result: WP auto break the line like:
------------------Starting of Editor ---------------------
Â
a |<-- caret position

---------------------------------------------------------------
Same bug with another character like E and E -> Ê , D and D -> Đ, U and W -> Ư, O and W -> Ơ , U and J -> Ụ , O and J -> Ọ...

**Comment by rachelmcr** [comment]
Thank you for reporting this! The issue you described sounds like one that was reported for Korean keyboards, as well: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/705

I'm going to close this report in favor of that one, and add the details from this report there.
