### ISSUE TITLE
how to suppurt more system versions?

### ISSUE THREAD

**Issue by hackjie** [wordpress-mobile/WordPress-Editor-iOS#809]
Hi, it requires iOS9,if i want to support more versions, for example iOS7 — iOS8, what should i do to change as quickly as possible, thanks

**Comment by SergioEstevao** [comment]
Hi there for you to use the current version of the pod you will need to remove the use of API calls that are iOS 9 and also to rollback some fixes that where specific for iOS 7.

I think the easiest way will be to use to version 0.9.1 of the pod, that was the last version that supported iOS 7 and above.

**Comment by hackjie** [comment]
ok, thanks for your answer, i will try version 0.9.1 of the pod and test
it, thanks again, haha


2016-04-22 16:43 GMT+08:00 Sérgio Estêvão <notifications@github.com>:
