### ISSUE TITLE
Apps that use non-public APIs will be rejected

### ISSUE THREAD

**Issue by huang5556019** [wordpress-mobile/WordPress-Editor-iOS#810]
Your app uses or references the following non-public APIs, which is a violation of the App Store Review Guidelines:

UIWebBrowserView

The use of non-public APIs is not permitted in the App Store because it can lead to a poor user experience should these APIs change.

anyone has solutions?

**Comment by diegoreymendez** [comment]
We're actually not using any private APIs.

More specifically:
- Navigating the view hierarchy requires no private APIs.
- Comparing an object's class name to a string requires no private APIs.
- Swizzling methods requires no private APIs.

**Comment by diegoreymendez** [comment]
Just to give a bit more info about this, we're not aware of any way around this solution at this time.

Closing.
