### ISSUE TITLE
Non breaking blank spaces being added to the post titles.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Editor-iOS#813]
Example: https://astralimagery.com/2016/05/02/tulips%EF%BB%BF/

Make sure that's not feasible anymore.

**Steps to reproduce:** (updated on 2016-05-03)
1. Open the editor
2. Make sure the title is focused. If it's not, tap on it.
3. Use the site picker to switch sites
4. Enter a post title (without ever tapping backspace)
5. Publish post

**Comment by rachelmcr** [comment]
I believe the issue is unrelated to the post content, and is actually related to the site picker in the editor. I can reproduce this issue consistently with these steps:

1. Open the editor
2. Use the site picker to switch sites
3. Enter a post title
4. Publish post

**Comment by astralbodies** [comment]
@rachelmcr You're completely right - I had to switch sites before I posted that picture. Genius!

**Comment by diegoreymendez** [comment]
@rachelmcr - These are the steps for 100% repro here... slightly modified version of your list, thanks!

1. Open the editor
2. Make sure the title is focused.  If it's not, tap on it.
3. Use the site picker to switch sites
4. Enter a post title
5. Publish post

**Comment by diegoreymendez** [comment]
Update: it seems that the reason why we're seeing the weird character being added to the title, is that a library we're using to backup and restore the selection is inserting them for marking purposes.

The code that's causing things to break is [this call](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Classes/WPEditorViewController.m#L157), which in turn is triggering [this](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L217) javascript method.

Right after that, we handle [the blur even in javascript](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L2429) which in turn tries to [empty the field](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Assets/ZSSRichTextEditor.js#L2404) if it has no visible content.  The reason we do this, is to make sure the placeholder text is shown to the user when there's no visible content.

The method fails to empty its contents, because it's not checking for the markers that rangy inserts and considers them to be valid content (in fact if you reproduce this bug, you'll notice the title field is empty when opening the site picker).

**Comment by diegoreymendez** [comment]
Fixed in v1.7.
