### ISSUE TITLE
Module 'NSOBject_SafeExpectations' not found

### ISSUE THREAD

**Issue by GioValentin** [wordpress-mobile/WordPress-Editor-iOS#826]
Hey guys hopefully someone can help me out. I am new to the iOS development, I used pod to install the framework and when I went to simulate the project it through this error pod  Module 'NSOBject_SafeExpectations' not found in the WPImageMeta.h file.

Thanks in advance

**Comment by GiovanniValen** [comment]
UPDATE: you just need to uncomment the "use frameworks!"
