### ISSUE TITLE
Image Toolbar Button Not working

### ISSUE THREAD

**Issue by GioValentin** [wordpress-mobile/WordPress-Editor-iOS#828]
Hey guys I implemented the texteditor in my App and I can't seem to get the Image deal to work. Is there a certain way to implement the editor for the Image Button to work?

**Comment by SergioEstevao** [comment]
Hi Gio, 

Are you talking about the button in the toolbar to insert images? or the option to edit image attributes after the image is added to the post?

Cheers,

**Comment by GioValentin** [comment]
I figured it out. I am not using a navigation controller so I had to just use self instead of self.navigation controller dismiss. Thank you for the reply back.
