### ISSUE TITLE
Can't schedule a post on iPhone 5 - publish settings are broken

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-iOS#846]
### Expected behavior

In the post settings, I expect to be able to select a publish date for my post and schedule or backdate it.
### Actual behavior

On the iPhone 5, the date selector is broken and I can't schedule/backdate posts. (The date selector is also broken on the iPhone 5s, but if you select a past/future date you can still backdate/schedule posts as expected.)

The blue bar at the top of the date selector is missing:

![simulator screen shot aug 10 2016 10 29 23 am](https://cloud.githubusercontent.com/assets/8658164/17549363/b6ef55d0-5ee7-11e6-95ea-7b52622be17a.png)

And after I select a future date, the post status still only gives the "Published" option (instead of switching to a "Scheduled" option):

![simulator screen shot aug 10 2016 10 30 04 am](https://cloud.githubusercontent.com/assets/8658164/17549374/cc28ff14-5ee7-11e6-8621-4bdb4672e32a.png)
### Steps to reproduce
1. Using an iPhone 5 (or iPhone 5 emulator) open the app
2. Start a new post
3. Open the post settings
4. Tap on Publish to open the date selector and note the missing bar at the top of the date selector
5. Select a future date
6. Tap on Status and note that there is a `Published` status option instead of `Scheduled`.

**Comment by frosty** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/6231#merged-event%23merged-event
