### ISSUE TITLE
Shortcode handling

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#85]
This is how it looks now:

![scaled screenshot 2014 07 25 15 24 04](https://cloud.githubusercontent.com/assets/154014/3707787/c1ffd666-1439-11e4-959b-3a39bad3cd16.png)

Probably should handle it in a cleaner way.

**Comment by meremagee** [comment]
since we handle captions visually inline, closing this and opening a more detailed issue for broader shortcode handling
