### ISSUE TITLE
I want to textview, not view controller.

### ISSUE THREAD

**Issue by Ying1986** [wordpress-mobile/WordPress-Editor-iOS#851]
How can I use this library as View, instead of ViewController.

I need to add sub-view that has rich-text edit function with toolbar.

**Comment by diegoreymendez** [comment]
There are no plans right now to implement this editor as a view.

That said, you should probably try out [the new Aztec native editor](https://github.com/wordpress-mobile/AztecEditor-iOS) which is available as a view.
