### ISSUE TITLE
GPL is incompatible with iOS development.

### ISSUE THREAD

**Issue by al45tair** [wordpress-mobile/WordPress-Editor-iOS#864]
The GPL is fundamentally incompatible with iOS development. You _cannot_ comply with both the terms of Apple's Developer Program and with the terms of the GPL. Thus releasing iOS code under GPL and claiming it is "Open Source" is, at best, misleading.

Additionally, you haven't properly acknowledged all of the non-GPL'd code in this project; your LICENSE file only includes a copy of the GPL, whereas it should include copies of all the other licenses that apply, and there are files in your project (WPEditorView.m in particular) that appear at first glance to be derived from code subject to someone else's copyright but where the copyright notice has been removed or omitted somehow.

**Comment by diegoreymendez** [comment]
```
The GPL is fundamentally incompatible with iOS development. You cannot comply with both the terms of Apple's Developer Program and with the terms of the GPL. Thus releasing iOS code under GPL and claiming it is "Open Source" is, at best, misleading.
```

I'd recommend contacting the [WordPress Foundation directly](http://wordpressfoundation.org/contact) to address any concerns with our software being in the iOS App Store.

```
Additionally, you haven't properly acknowledged all of the non-GPL'd code in this project; your LICENSE file only includes a copy of the GPL, whereas it should include copies of all the other licenses that apply
```

Thanks for pointing this out.  We've just added a local copy of the license files to make sure we're complying with their terms.

```
and there are files in your project (WPEditorView.m in particular) that appear at first glance to be derived from code subject to someone else's copyright but where the copyright notice has been removed or omitted somehow.
```

We've just added copyright notices to WPEditorView.h and WPEditorView.m to clear out any confusion regarding attribution and copyright.

I've reviewed the file's [initial commit](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/166/commits/cefe26897ed8de7b95f9e746d8ff8f6ac61090c4), and it seems that some of the code is indeed coming from ZSSRichTextEditor.h and ZSSRichTextEditor.m, but failed to keep the copyright notices.
