### ISSUE TITLE
The content lost at the first time you end editing.

### ISSUE THREAD

**Issue by Homosum** [wordpress-mobile/WordPress-Editor-iOS#872]
The first time you launch the vc and ,add some words into the editorView, then tap the edit button to end editing. As you tapped ,your contents in the editorView all disappeared,showing a empty view to the fore.
But the second time you restart editing at this vc ,this emptying-contents problem disappeared.
I reviewed the code for days , hasn't found a way to solve it.
another question is "if  I can left the toorBar at the bottom of the view when I end editing?", Not let the toorBar disappearing with the keyboard, can this function achieve?
wish my poor english has described my problems clear,
sincerely.

**Comment by Homosum** [comment]
Another problem is the 'redo' and 'undo'  js-founctions does not work.

**Comment by Homosum** [comment]
0ne more problem  is that the 'Bold' function doesn't work until the keyboard has put out words twice, besides 'Italic' function and so on.

**Comment by Homosum** [comment]
0ne more problem  is that the 'Bold' function doesn't work until the keyboard has put out words twice, besides 'Italic' function and so on.

**Comment by yuyedaidao** [comment]
the some problem

**Comment by yuyedaidao** [comment]
Help me!

**Comment by rachelmcr** [comment]
Thank you for reporting these issues. There are open issues for the disappearing content in the demo app (https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/856), the undo/redo functionality (https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/496), and starting a post with formatted text (https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/754).

Patches for those issues are welcome. :) However, our current development focus is on a new, native editor: https://github.com/wordpress-mobile/AztecEditor-iOS
