### ISSUE TITLE
Hello, I got stuck with implement the delegate

### ISSUE THREAD

**Issue by mozhanmeng** [wordpress-mobile/WordPress-Editor-iOS#885]
Hi, I am using swift3.  Could anyone give me a hand?

import UIKit
import WordPressEditor

class PostNewsViewController: WPEditorViewController, WPEditorViewControllerDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.delegate = self
    }

I can't implement the delegate. Did I do something wrong?

And another question..
  It appears to not response when I click on the media(the first button of tool bar). Do I need to do the uploading media part by myself? Or it is done already.. But Why it does not response while other button perform well.

**Comment by catehstn** [comment]
Hi! This editor is deprecated and no longer updated. Can I suggest you take a look at Aztec instead? https://github.com/wordpress-mobile/AztecEditor-iOS
