### ISSUE TITLE
Difference between ios wordpress 8.4 and sample 1.9.5

### ISSUE THREAD

**Issue by qiaoyan** [wordpress-mobile/WordPress-Editor-iOS#896]
Replicate steps: (iOS version 10.3.3)
1) click "bold" button; 
2) type 'bold'; 
3) click "bold" button; 
4) type 'normal'; 
5) enter;
6) switch to "bold" input status by try input and delete; 
7) type chinese character '粗体'; 
8) click "bold" button; 
9) type chinese character '正常体' 

The result in ios wordpress is the expectation. 

In sample version 1.9.5, a) first character won't be bold, and b) for chinese character won't change from bold to normal in the same line, but it can be changed from normal to bold. I also try japanese character the same result.

**wordpress 8.4**
![img_1252](https://user-images.githubusercontent.com/1080270/30897453-f0b50a44-a388-11e7-9378-85c339fd39f4.PNG)

**sample 1.9.5**
![img_1253](https://user-images.githubusercontent.com/1080270/30897460-f52f4418-a388-11e7-9259-b1fe6d47c6c2.PNG)

**Comment by elibud** [comment]
@diegoreymendez do you want to move this to the Aztec repo?

**Comment by qiaoyan** [comment]
for reference, behavior corrent in AztecEditor-iOS version 1.0.0-beta.12, but not in earlier version.

![](https://user-images.githubusercontent.com/1080270/31478778-585976fe-af45-11e7-9b27-617108e7f8a8.jpeg)

**Comment by elibud** [comment]
Thanks @qiaoyan 
@diegoreymendez is this OK to close?

**Comment by diegoreymendez** [comment]
@qiaoyan - Can you confirm this is not a problem anymore?

**Comment by qiaoyan** [comment]
Hi, I think it is not a problem for [AztecEditor-iOS](https://github.com/wordpress-mobile/AztecEditor-iOS)

**Comment by diegoreymendez** [comment]
Closing then.  Thanks!
